### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by TkIgor** [valyala/ybc#12]
Hello. I get the following trying to build. 
GOPATH="/var/www/toxbid/feeds/pgsql/gopath:/var/www/toxbid/feeds/pgsql" go build -ldflags '-L/var/www/toxbid/feeds/pgsql/gopath/src/github.com/valyala/ybc/ -s' -o /var/www/toxbid/feeds/pgsql/feed-server-pgsql /var/www/toxbid/feeds/pgsql/main.go
github.com/valyala/ybc/bindings/go/ybc
In file included from gopath/src/github.com/valyala/ybc/bindings/go/ybc/ybc.c:1:0:
gopath/src/github.com/valyala/ybc/bindings/go/ybc/platform.h:240:30: fatal error: platform/linux.c: No such file or directory
compilation terminated.
make: *** [feed-server-pgsql] Error 2

**Comment by valyala** [comment]
It looks like you somehow missed a symlink to platform directory in bindings/go/ybc/ . The directory contents must look like:

```
$ ls -l bindings/go/ybc/
total 172
lrwxrwxrwx 1 valyala valyala    17 Nov 17  2012 config.h -> ../../../config.h
-rw-rw-r-- 1 valyala valyala  2770 Nov 17  2012 debugguard_devel.go
-rw-rw-r-- 1 valyala valyala   977 Nov 17  2012 debugguard_release.go
-rw-rw-r-- 1 valyala valyala  4979 Jan  4  2013 perf_test.go
lrwxrwxrwx 1 valyala valyala    17 Nov  4  2012 platform -> ../../../platform
lrwxrwxrwx 1 valyala valyala    19 Nov  4  2012 platform.h -> ../../../platform.h
-rw-rw-r-- 1 valyala valyala   888 Sep 22  2014 README
lrwxrwxrwx 1 valyala valyala    14 Nov  4  2012 ybc.c -> ../../../ybc.c
-rw-rw-r-- 1 valyala valyala  5789 Nov 17  2012 ybc_devel_test.go
-rw-rw-r-- 1 valyala valyala 32087 Feb  2  2015 ybc.go
-rw-rw-r-- 1 valyala valyala  1238 Sep 12  2013 ybc_go_glue.c
lrwxrwxrwx 1 valyala valyala    14 Nov  4  2012 ybc.h -> ../../../ybc.h
-rw-rw-r-- 1 valyala valyala 22705 Apr 10  2013 ybc_test.go
```

Notice symlinks above.

As a workaround, just re-create missing symlinks or just copy files and platform directory instead of missing symlinks.
